USE [master]
GO

/****** Object:  Database [SorteosTec]    Script Date: 18/05/2023 01:59:18 p. m. ******/
CREATE DATABASE [SorteosTec]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SorteosTec', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SorteosTec.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SorteosTec_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SorteosTec_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SorteosTec].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SorteosTec] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SorteosTec] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SorteosTec] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SorteosTec] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SorteosTec] SET ARITHABORT OFF 
GO

ALTER DATABASE [SorteosTec] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SorteosTec] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SorteosTec] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SorteosTec] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SorteosTec] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SorteosTec] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SorteosTec] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SorteosTec] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SorteosTec] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SorteosTec] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SorteosTec] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SorteosTec] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SorteosTec] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SorteosTec] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SorteosTec] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SorteosTec] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SorteosTec] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SorteosTec] SET RECOVERY FULL 
GO

ALTER DATABASE [SorteosTec] SET  MULTI_USER 
GO

ALTER DATABASE [SorteosTec] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SorteosTec] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SorteosTec] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SorteosTec] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SorteosTec] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SorteosTec] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SorteosTec] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SorteosTec] SET  READ_WRITE 
GO

